#pragma once

#include "CLI/Subcommand.h"

class QIODevice;

namespace CargoNetSim {
namespace Cli {

/**
 * @brief Pseudo-subcommand backing the `--help` and `-h` invocations.
 *
 * Plan 5 Task 11. Reads the embedded `help.txt` resource (single
 * source of truth for the user-facing help text) and writes it to
 * the output sink. Always returns `ExitCode::Success` on a clean
 * read; `ExitCode::BadArgs` only if the embedded resource cannot be
 * opened (build-time misconfiguration).
 *
 * Output sink: the optional `QIODevice *` constructor parameter is a
 * test injection seam — production wiring (`main.cpp` Task 18) uses
 * the default constructor which writes to stdout. The injected
 * device must outlive the command instance.
 */
class HelpCommand : public Subcommand
{
public:
    explicit HelpCommand(QIODevice *out = nullptr);
    int execute(const QStringList &args) override;

private:
    QIODevice *m_out;  // not owned; nullptr → write to stdout
};

/**
 * @brief Pseudo-subcommand backing the `--version` and `-v`
 *        invocations.
 *
 * Reads the project version macro generated by CMake into
 * `Version.h` (`CARGONETSIM_VERSION`) and writes a single line:
 * `cargonetsim-cli <version>\n`. Same test-injection seam as
 * `HelpCommand`.
 */
class VersionCommand : public Subcommand
{
public:
    explicit VersionCommand(QIODevice *out = nullptr);
    int execute(const QStringList &args) override;

private:
    QIODevice *m_out;
};

} // namespace Cli
} // namespace CargoNetSim
